"""
Django settings for dictionary_project project.

Generated by 'django-admin startproject' using Django 5.0.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path
import os
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-+^bn&e6uklss4jeg5%pw3o9w37yunl)zl#t^^x0+8)e!t5w3!9'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'captcha',
    'accounts',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',  # مدیریت نشست
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',  # احراز هویت
    'django.contrib.messages.middleware.MessageMiddleware',
]


AUTH_USER_MODEL = 'accounts.User'
ROOT_URLCONF = 'dictionary_project.urls'
STATIC_URL = '/static/'

STATICFILES_DIRS = [
    BASE_DIR / "accounts"/"static",  # محل فایل‌های استاتیک پروژه
]

LOGIN_URL = '/accounts/login/'  # مسیر صفحه ورود
LOGIN_REDIRECT_URL = '/accounts/manage/'  # مسیر پیش‌فرض پس از ورود موفق


TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR,'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'dictionary_project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'mssql',
        'NAME': 'dictionary_db',  # نام دیتابیس شما
        'USER': 'root',  # نام کاربری SQL Server
        'PASSWORD': 'Classroom80kh5t',  # رمز عبور SQL Server
        'HOST': 'localhost',  # یا نام سرور شما
        'PORT': '1433',  # پورت پیش‌فرض SQL Server
        'OPTIONS': {
            'driver': 'ODBC Driver 17 for SQL Server',  # مطمئن شوید این درایور نصب است
        },
    }
}




# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        'OPTIONS': {
            'min_length': 8,
        },
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]



# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

LOGIN_REDIRECT_URL = '/accounts/manage/'  # مسیر پیش‌فرض پس از ورود موفق
AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
]
SESSION_COOKIE_AGE = 600  # زمان اعتبار کوکی (در ثانیه،10 دقیقه)
SESSION_SAVE_EVERY_REQUEST = True  # تمدید زمان نشست با هر درخواست
SESSION_COOKIE_SECURE = False  # فقط در HTTPS آن را True کنید
EMAIL_HOST = 'smtp.gmail.com'  # یا هر سرویس ایمیل دیگری
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'hadikaramy.hk@gmail.com'  # ایمیل خودتان
EMAIL_HOST_PASSWORD = 'sfkyhzjjwwsqkejv'  # رمز عبور ایمیل شما

# بستن نشست پس از بستن مرورگر
SESSION_EXPIRE_AT_BROWSER_CLOSE = True

# فعال کردن انقضای نشست به‌صورت مطلق
SESSION_EXPIRE_AFTER_LAST_ACTIVITY = True
